---
pops_secrets:
  - name: notion_api_token
    value: "{{ vault_notion_api_token }}"
  - name: up_bank_token
    value: "{{ vault_up_bank_token }}"
  - name: up_webhook_secret
    value: "{{ vault_up_webhook_secret }}"
  - name: claude_api_key
    value: "{{ vault_claude_api_key }}"
  - name: telegram_bot_token
    value: "{{ vault_telegram_bot_token }}"
  - name: finance_api_key
    value: "{{ vault_finance_api_key }}"
  - name: cloudflare_tunnel_token
    value: "{{ vault_cloudflare_tunnel_token }}"
  - name: paperless_secret_key
    value: "{{ vault_paperless_secret_key }}"
  - name: paperless_admin_password
    value: "{{ vault_paperless_admin_password }}"
