all:
  children:
    pops_servers:
      hosts:
        n95:
          ansible_host: pops.local
          ansible_port: 2222
          ansible_user: pops
          ansible_ssh_private_key_file: ~/.ssh/pops_n95
          ansible_python_interpreter: /usr/bin/python3
