---
- name: Create secrets directory
  ansible.builtin.file:
    path: "{{ secrets_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0700"

- name: Write secret files
  ansible.builtin.copy:
    content: "{{ item.value }}"
    dest: "{{ secrets_dir }}/{{ item.name }}"
    owner: root
    group: root
    mode: "0600"
  loop: "{{ pops_secrets }}"
  no_log: true
